### ISSUE TITLE
Storybook and Widgets source code separation

### ISSUE THREAD

**Issue by Pooya-Oladazimi** [ts4nfdi/terminology-service-suite#143]
I would like to know why we combined the storybook source code and the widgets? I mean why not create a repo for the widgets alone? since consumer projects will use the widgets as their library, not the storybook. Mixing these two has some downsides imo:

The versioning is not correct since it reflects both the changes of the widgets and the storybook at the same time. For example, this release only has a change regarding the storybook and not the widgets. Since consumers care about the changes in the widgets, this can create confusion. Like, should I update this library or not? 
![Screenshot from 2024-10-10 10-47-39](https://github.com/user-attachments/assets/2f3e1267-d84a-4c4f-b263-80c063c6b7ee)

Besides, it makes testing and debugging a bit cumbersome for us. Sometimes it is not clear that the problem is with the widgets or the storybook.

**Comment by rombaum** [comment]
@Pooya-Oladazimi You are correct with this point. However I would not split this up at the moment since we could invest the time better and we also got very nice feedback for the current status. I removed the authors for privacy reasons:

Feedback 1st person:
![grafik](https://github.com/user-attachments/assets/441aa4f0-2ffd-473e-a4a0-07d75dbad453)

Feedback 2nd person:
![grafik](https://github.com/user-attachments/assets/7ab5967d-c1d8-4868-a3ab-1b1424238180)
